events {}

http {
    upstream validador_service {
        server validador:5000;
    }

    upstream ordenes_service {
        server ordenes1:5000;
        server ordenes2:5000;
        server ordenes3:5000;
    }

    server {
        listen 80;

        location /consulta-ordenes {
            proxy_pass http://validador_service/process;
        }

        location /api-health {
            proxy_pass http://validador_service/health;
        }

        location /ordenes/ {
            proxy_pass http://ordenes_service/;
        }
    }
}
