events {}

http {
    upstream validador_service {
        server validador:5000;
    }

    upstream pedidos_service {
        server pedidos1:5000;
        server pedidos2:5000;
        server pedidos3:5000;
    }

    server {
        listen 80;

        location /consulta-pedidos {
            proxy_pass http://validador_service/process;
        }

        location /api-health {
            proxy_pass http://validador_service/health;
        }

        location /pedidos/ {
            proxy_pass http://pedidos_service/;
        }
    }
}
